In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df=pd.read_csv('cancer dataset1.csv') 

In [6]:
from sklearn.preprocessing import LabelEncoder
labelencoder_Y=LabelEncoder()
df.iloc[:,1]=labelencoder_Y.fit_transform(df.iloc[:,1].values)

In [7]:
X=df.iloc[:,2:31].values 
Y=df.iloc[:,1].values

In [8]:
# Split the data into 75% training and 25% testing
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test= train_test_split(X,Y, test_size=0.25, random_state=0)

In [9]:
# Scale the data (Feature scaling)
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [10]:
# Create a function for model Logistic Regression
def logreg (X_train, Y_train):
    from sklearn.linear_model import LogisticRegression
    log=LogisticRegression (random_state=0)
    log.fit(X_train, Y_train)
    print("Logistic Regression Training Accuracy:", log.score(X_train, Y_train))
    return log

In [11]:
logrex=logreg(X_train, Y_train) 

Logistic Regression Training Accuracy: 0.9906103286384976


In [12]:
# Confusion Matrix
# A confusion matrix is a summary of prediction results on a classification problem. The number of correct and incorrect predictions are summarized with count values and broken down by each class. This is the key to the confusion matrix. The confusion matrix shows the ways in which your classification model is confused when it makes predictions. It gives us insight not only into the errors being made by a classifier but more importantly the types of errors that are being made.

# Definition of the Terms:
# Positive (P) : Observation is positive (for example: is an apple). Negative (N) : Observation is not positive (for example: is not an apple). True Positive (TP) : Observation is positive, and is predicted to be positive. False Negative (FN) : Observation is positive, but is predicted negative. True Negative (TN) : Observation is negative, and is predicted to be negative. False Positive (FP) : Observation is negative, but is predicted positive.

# Rates that are often computed from a confusion matrix for a binary classifier:

# Accuracy: Overall, how often is the classifier correct? (TP+TN)/total

# Misclassification Rate: Overall, how often is it wrong? (FP+FN)/total

In [13]:
# Test model accuracy on test data on confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, logrex.predict(X_test))
print(cm)

[[86  4]
 [ 3 50]]


In [14]:
# In this model

# true positive=86
# True negative=50
# False positive=4
# # False negative=3

In [15]:
TP=cm[0][0]
TN=cm[1][1]
FN=cm[1][0]
FP=cm[0][1]
print("Testing accuracy of logistic regression model=", (TP+TN)/(TP+TN+FN+FP))

Testing accuracy of logistic regression model= 0.951048951048951


In [20]:
# Create a function for model Decision Tree 
def dectree (X_train, Y_train):
    from sklearn.tree import DecisionTreeClassifier
    tree=DecisionTreeClassifier (random_state=0)
    tree.fit(X_train, Y_train)
    print("Decision Tree Training Accuracy:", tree.score(X_train, Y_train))
    return tree

In [21]:
acc_dectree=dectree(X_train, Y_train)

Decision Tree Training Accuracy: 1.0


In [30]:
# Test model accuracy on test data on confusion matrix
from sklearn.metrics import confusion_matrix
cm2 = confusion_matrix(Y_test, acc_dectree.predict(X_test))
print(cm2)

[[79 11]
 [ 3 50]]


In [31]:
TP2=cm2[0][0]
TN2=cm2[1][1]
FN2=cm2[1][0]
FP2=cm2[0][1]
print("Testing accuracy of Decision Tree model=", (TP2+TN2)/(TP2+TN2+FN2+FP2))

Testing accuracy of Decision Tree model= 0.9020979020979021


In [32]:
# Create a function for model Random Forest
def ranforest (X_train, Y_train):
    from sklearn.ensemble import RandomForestClassifier
    forest=RandomForestClassifier (random_state=0)
    forest.fit(X_train, Y_train)
    print("Random Forest Training Accuracy:", forest.score(X_train, Y_train))
    return forest

In [33]:
acc_ranforest=ranforest(X_train, Y_train)

Random Forest Training Accuracy: 0.9976525821596244


In [34]:
# Test model accuracy on test data on confusion matrix
from sklearn.metrics import confusion_matrix
cm3 = confusion_matrix(Y_test, acc_ranforest.predict(X_test))
print(cm3)

[[85  5]
 [ 1 52]]


In [36]:
TP3=cm3[0][0]
TN3=cm3[1][1]
FN3=cm3[1][0]
FP3=cm3[0][1]
print("Testing accuracy of Random Forest model=", (TP3+TN3)/(TP3+TN3+FN3+FP3))

Testing accuracy of Random Forest model= 0.958041958041958


In [ ]:
# Random Forest Classifier has highest accuracy (0.958041958041958) among the other two classifiers.
# Random forest algorithm creates decision trees on data samples and then gets the prediction from each of them and finally selects the best solution by means of voting.
# Hence Random Forest Classifier is the best model as it gives the best results for our dataset.